### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by alekovargas** [google-coral/py-repo#3]
Hello. i am having some problems running the python3 examples/classify_image.py \in MAC os Catalina 10.15.7, it seems edgetpu image is missing,  as follow;

> --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --labels test_data/inat_bird_labels.txt \
> --input test_data/parrot.jpg
Traceback (most recent call last):
  File "examples/classify_image.py", line 39, in <module>
    from pycoral.utils.edgetpu import make_interpreter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycoral/utils/edgetpu.py", line 24, in <module>
    from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycoral/pybind/_pywrap_coral.cpython-38-darwin.so, 2): Library not loaded: @rpath/libedgetpu.1.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycoral/pybind/_pywrap_coral.cpython-38-darwin.so
  Reason: image not found

--------
this might be due to the fact that  Edge TPU runtime fails to be installed using: 

curl -O https://github.com/google-coral/libedgetpu/releases/download/release-frogfish/edgetpu_runtime_20210119.zip
unzip edgetpu_runtime_20210119.zip 

MacBook-Pro:pycoral user$ unzip edgetpu_runtime_20210119.zip
Archive:  edgetpu_runtime_20210119.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of edgetpu_runtime_20210119.zip or
        edgetpu_runtime_20210119.zip.zip, and cannot find edgetpu_runtime_20210119.zip.ZIP, period. 

it seems file is corrupted,

**Comment by alekovargas** [comment]
closed and reported in the https://github.com/google-coral/edgetpu/issues
